spring.application.name=IRAUS


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/IRSU?createDatabaseIfNotExist=true
# DB Credentials
spring.datasource.username=root
spring.datasource.password=kumari8899
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true


spring.security.user.name=user
spring.security.user.password=12345